### ISSUE TITLE
Tone.Synth() throws this._readOnly is not a function on Ionic

### ISSUE THREAD

**Issue by Gimly** [Tonejs/Tone.js#271]
I'm trying to get Tone.js working on Ionic Framework 3.8, I imported the library and tried a very simple page that instanciates a new Synth, but I'm getting `this._readOnly is not a function`.

Here's the code of the test page I created, the error happens directly when I do `Tone.Synth()`.

```Typescript
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import * as Tone from 'tone';

@IonicPage()
@Component({
  selector: 'page-tone',
  templateUrl: 'tone.html',
})
export class TonePage {

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

  ionViewDidLoad(): void {
      const synth = Tone.Synth();
      synth.ToMaster();
  }
}

```

**Comment by tambien** [comment]
All the classes in Tone.js need to be called with the 'new' keyword. This should be fixed if you change that one line to:

```javascript
const synth = new Tone.Synth();
```

**Comment by Gimly** [comment]
Oh, sorry about that, I was so focused on something else that I didn't see the obvious. Thanks for the help !
